name: app

type: php:7.4

runtime:
    extensions:
        - pdo_pgsql
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        - redis
        - amqp
        - xsl
       

#variables:
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: /app/config/preload.php

build:
    flavor: none
relationships:
    database: "db:postgresql"
    redis: "rediscache:redis"
    rabbitmq: "queue:rabbitmq" 
disk: 512

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"



mounts:
    "/var": { source: local, source_path: var }
    "/public/images": { source: local, source_path: images }

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)
workers:
    messages:
        commands:
            start: |
                set -x -e

                (>&2 symfony-deploy)
                php bin/console messenger:consume async -vv --time-limit 3600 --memory-limit=128M
