db:
  type: postgresql:11
  disk: 1024
  size: S
myredis:
  # supported versions: 3.2, 4.0, 5.0, 6.0
  # 2.8 and 3.0 are also available but not maintained upstream
  type: redis-persistent:6.0
  disk: 1024
